# This file maps each competency to its behavioral interview prompts extracted from Competecies:interview Questions.rtf
# Format: { "Competency Name": [list of prompts], ... }
COMPETENCY_QUESTIONS = {
    "Action Oriented": [
        "Share an experience when faced with a difficult and urgent problem.",
        "Share an experience when you had to take over someone else’s challenging project.",
        "Share an experience when a situation required an enormous amount of energy and effort.",
        "Share an experience when you demonstrated a can-do attitude.",
        "Share an experience when you acted too hastily and had to deal with the consequences.",
        "Share an experience when you were eager to address an issue, yet first needed others’ buy-in.",
        "Share an experience when you seized an opportunity and moved forward with it yourself.",
        "Share an experience when you identified a new opportunity worth pursuing.",
        "Share an experience when you were the first person to take action on something.",
        "Share an experience when you had to decide between more planning or taking immediate action.",
        "Explain what you did when faced with a difficult and urgent problem.",
        "Tell me about a time you had to take over someone else's challenging project.",
        "Tell me about a situation that required an enormous amount of energy and effort.",
        "Describe a time you seized an opportunity and moved forward with purpose.",
        "Tell me about a time you were the first person to take action on something.",
        "Describe a time when you were proactive in addressing a potential problem.",
        "Tell me about a time you took a calculated risk and it paid off.",
        "Explain a situation where you had to juggle multiple high-priority tasks."
    ],
    "Balances Stakeholders": [
        "Share an experience when you had to work with external stakeholders to get business results.",
        "Share an experience when you could have worked with external stakeholders better.",
        "Share an experience when you had to make a high-stakes decision that took into account different stakeholder needs.",
        "Share an experience when you needed to manage expectations of stakeholders whose views were different from your own.",
        "Share an experience when you had to change a process or procedure to make it fair for everyone.",
        "Share an experience when you had to factor competing stakeholder perspectives into a decision.",
        "Share an experience when you anticipated stakeholder needs and addressed them proactively.",
        "Share an experience when you did not gather enough input from all stakeholders.",
        "Share an experience when stakeholders disagreed on a course of action and you had to find middle ground.",
        "Share an experience when you had to manage a difficult stakeholder."
    ],
    "Being Resilient": [
        "Share an experience when you had to handle a crisis.",
        "Share an experience when you managed an emergency situation.",
        "Share an experience when you dealt with a hardship assignment or situation (for example, layoffs, legal or regulatory battles, trouble with unions).",
        "Share an experience when you rebounded from a negative work experience.",
        "Share an experience when you were under extreme pressure but managed to carry on.",
        "Share an experience when you were under pressure to back down but stood firm.",
        "Share an experience when a project or initiative seemed like it was going nowhere.",
        "Share an experience when you absolutely knew you were right and others around you doubted you.",
        "Share an experience when someone or something caught you by surprise and caused you to be blocked.",
        "Share an experience when you became defensive or irritated and were able to successfully regain your focus.",
        "Describe a crisis you had to handle.",
        "Give me an example of how you managed an emergency situation.",
        "Tell me about a time when you felt under extreme pressure but managed to carry on.",
        "Tell me about a time when a project or initiative seemed like it was going nowhere.",
        "Tell me about a time when someone or something caught you by surprise and caused you to be blocked.",
        "Describe a time when you had to adapt to a significant change at work.",
        "Tell me about a time you received constructive criticism and how you handled it.",
        "Explain a situation where you had to maintain your composure in a challenging circumstance."
    ],
    "Builds Networks": [
        "Share an experience when you needed to connect people in order to accomplish a goal.",
        "Share an experience when you connected two people who previously didn’t know each other.",
        "Share an experience when you used your network to exchange ideas, resources, and knowledge.",
        "Share an experience when you leveraged your network to gain knowledge for one of your projects.",
        "Share an experience when you used your connections to shape an initiative.",
        "Share an experience when you were able to resolve a problem or conflict by reaching out to your network.",
        "Share an experience when you benefited from a partnership with another person or organization.",
        "Share an experience when having a strong network made things work better or faster for you.",
        "Share an experience when you built strong relationships that lasted beyond a single project or initiative.",
        "Share an experience when you removed barriers to get others to build relationships across organizational boundaries."
    ],
    "Business Insight": [
        "Share an experience when you’ve had about your organization’s competitors.",
        "Share an experience when you keep current on competitors and how those insights are predicting your organization’s next steps.",
        "Share an experience when your knowledge of marketplace trends influenced a decision you made.",
        "Share an experience when you made a decision that had a positive impact on the business as a whole.",
        "Share an experience when you learned about a failing business and why you think it is struggling.",
        "Share an experience when you developed your knowledge of business.",
        "Share an experience when you learned about a successful business and why you think it is successful.",
        "Share an experience when you worked for a successful business and why?",
        "What trends do you see in your current industry?",
        "How do you keep yourself current on business practices and trends?"
    ],
    "Collaborates": [
        "Share an experience when you built strong relationships where none previously existed.",
        "Share an experience when you had to build partnerships to achieve a shared objective.",
        "Share an experience when you worked with multiple groups or people who had different interests.",
        "Share an experience when you worked to earn trust and credibility with your team.",
        "Share an experience when you had implementing something across organizational boundaries.",
        "Share an experience when you managed a system or process that enabled teamwork across organizational boundaries.",
        "Share an experience when a team or group did not get their share of credit.",
        "Share an experience when you were praised individually when others deserved credit too.",
        "Share an experience when you succeeded in an initiative by collaborating with others.",
        "Share an experience when you were only able to achieve your individual goals due to work from other team members.",
        "Tell me about a time when you built strong relationships where none previously existed.",
        "Describe a time you had to build partnerships to achieve a shared objective.",
        "Tell me about a successful experience you had implementing something across organizational boundaries.",
        "Describe a time when a team or group did not get their share of credit.",
        "Tell me about a time you succeeded in an initiative by collaborating with others.",
        "Explain a situation where you had to work with a difficult colleague and how you handled it.",
        "Describe a time when you had to coordinate with multiple teams to achieve a goal.",
        "Tell me about a time you had to manage conflicting priorities from different stakeholders."
    ],
    "Communicates Effectively": [
        "Share an experience when you had to explain something important to someone who did not understand your industry or function’s language or work.",
        "Share an experience when you were leading a group who didn’t know much about the task.",
        "Share an experience when you gave the best presentation you’ve ever given.",
        "Share an experience when you were comfortable with the message you communicated and felt you connected with your audience.",
        "Share an experience when others were missing the key points in a discussion and you helped get things back on track.",
        "Share an experience when you were involved in a task that required you to communicate clearly and quickly.",
        "Share an experience when you had to shut off a person in the middle of a meeting or who was talking too much or interrupting.",
        "Share an experience when someone said you weren’t listening but you think you were.",
        "Share an experience when you had to convey the same message through different methods of communication (for example, e-mail and a presentation, or a meeting and a phone call).",
        "Share an experience when you had to communicate the same message to different audiences and had to vary your style for each.",
        "Tell me about a time when you had to explain something important to someone who did not understand your industry or function's language or work.",
        "Describe the best presentation you've ever given.",
        "Tell me about a time when others were missing the key points in a discussion and you helped get things back on track.",
        "Tell me about a time you had to shut off a person in the middle of a meeting or who was talking too much or interrupting.",
        "Describe a time you had to convey the same message through different methods of communication.",
        "Explain a situation where you had to adjust your communication style to suit the audience.",
        "Tell me about a time when you used data or evidence to support your message.",
        "Describe a time when you had to persuade someone to see things your way."
    ],
    "Courage": [
        "Share an experience when you disagreed with someone more senior and offered a solution that was accepted.",
        "Share an experience when you challenged someone in a position of authority.",
        "Share an experience when you were investigating something and had to report back negative news to higher management.",
        "Share an experience when you had feedback on something someone did and wished you had said it.",
        "Share an experience when you challenged an idea or approach.",
        "Share an experience when you criticized the status quo despite some risk.",
        "Share an experience when you stepped in to defend someone else. Describe the impact when you felt it was being unfairly treated.",
        "Share an experience when you challenged someone on an ethical issue.",
        "Share an experience when you accepted an assignment where the odds were stacked against you.",
        "Share an experience when you volunteered for a risky or difficult project no one else wanted to do."
    ],
    "Cultivates Innovation": [
        "Share an experience when you had the most unusual idea you’ve had that worked.",
        "Share an experience when you made your most creative contribution to the organization.",
        "Share an experience when you came up with some new ideas to solve an old problem.",
        "Share an experience when you facilitated idea generating or brainstorming with others.",
        "Share an experience when you took a risk on a new product or solution and it paid off.",
        "Share an experience when you identified an opportunity to innovate during the early stages of a project or process.",
        "Share an experience when you managed something from the idea stage through to a successful application.",
        "Share an experience when you brought another person’s or group’s idea to a successful completion.",
        "Share an experience when you sized up an idea for its value in the market or organization.",
        "Share an experience when you participated in a failed attempt to innovate."
    ],
    "Customer Focus": [
        "Share an experience when you obtained up-to-date information from a customer, and what you did with it.",
        "Share an experience when new insights about a customer paid off.",
        "Share an experience when you went the extra mile for a challenging customer.",
        "Share an experience when you had to deal with what you thought were unreasonable customer requests.",
        "Share an experience when you were confronted with an internal or external customer problem.",
        "Share an experience when you found a customer problem especially difficult to deal with.",
        "Share an experience when you almost lost a customer and had to win them back.",
        "Share an experience when you exceeded a customer’s expectations.",
        "Share an experience when you changed your approach to better meet a customer’s needs.",
        "Share an experience when you created a new service, process, or product based on customer feedback.",
        "Describe a time you obtained up-to-date information from a customer, and what you did with it.",
        "Tell me about a time when you went the extra mile for a challenging customer.",
        "Tell me about a time you were confronted with an internal or external customer problem.",
        "Tell me about a time when you almost lost a customer and had to win them back.",
        "Tell me about a time when you changed your approach to better meet a customer's needs.",
        "Describe a time when you gathered customer feedback and how you used it.",
        "Tell me about a time you had to manage a customer's expectations.",
        "Explain a situation where you turned an unhappy customer into a satisfied one."
    ],
    "Decision Quality": [
        "Share an experience when you had to make a quick decision and gather a lot of information in a short time frame.",
        "Share an experience when you made a hasty decision and later regretted.",
        "Share an experience of a difficult problem you worked on and walk me through your decision-making process.",
        "Share an experience when you had to make a decision without all the information you wanted or needed.",
        "Share an experience when you made a major decision and were really pleased with the outcome.",
        "Share an experience when you made a significant decision but doubted yourself afterward.",
        "Share an experience of a quick decision you made that turned out to be a good one.",
        "Share an experience when you treated people with the speed at which you made decisions.",
        "Share an experience when you received useful feedback on a decision you made.",
        "Share an experience when you turned out to be right and others were wrong.",
        "Describe a time you had to make a quick decision and gather a lot of information in a short time frame.",
        "Give me an example of a difficult problem you worked on and walk me through your decision-making process.",
        "Describe a time when you made a major decision and were really pleased with the outcome.",
        "Tell me about a quick decision you made that turned out to be a good one.",
        "Describe a time when you received useful feedback on a decision you made.",
        "Tell me about a time when you had to decide between two equally qualified candidates.",
        "Explain a situation where you had to make a decision with incomplete information.",
        "Describe a time when you changed your mind about a decision and what prompted the change."
    ],
    "Drives Results": [
        "Share an experience when you championed a cause that others had abandoned.",
        "Share an experience when you got results that far exceeded your own expectations.",
        "Share an experience when you got results even though some major factor changed, such as a budget cut.",
        "Share an experience when you drove yourself harder than you were driving others.",
        "Share an experience when you were assigned to a fix-it or turnaround project.",
        "Share an experience when you had to overcome significant obstacles to achieve a goal.",
        "Share an experience when your persistence paid off in achieving a difficult objective.",
        "Share an experience when you had to motivate others to achieve results.",
        "Describe a time you championed a cause that others had abandoned.",
        "Tell me about a time you got results that far exceeded your own expectations.",
        "Tell me about a time you got results even though some major factor changed, such as a budget cut.",
        "Describe a time when you drove yourself harder than you were driving others.",
        "Talk about a time you were assigned to a fix-it or turnaround project.",
        "Explain a situation where you had to overcome significant obstacles to achieve a goal.",
        "Describe a time when your persistence paid off in achieving a difficult objective.",
        "Tell me about a time you had to motivate others to achieve results."
    ],
    "Strategic Mindset": [
        "Share an experience when you developed a new vision or strategy for your team or organization.",
        "Share an experience when you explored various scenarios and possibilities for the future.",
        "Share an experience when your strategic vision or big-picture thinking was an asset.",
        "Share an experience when you implemented a strategy and had to revise it mid-process due to changes in the environment.",
        "Share an experience when you developed a strategy that created value for your organization or customers.",
        "Share an experience when you had to align your team's goals with the organization's strategic objectives.",
        "Share an experience when you identified a long-term opportunity and acted on it.",
        "Share an experience when you had to convince others to buy into your strategic vision.",
        "Give me an example of working with a team and creating a new vision and strategy.",
        "Give me an example of exploring various scenarios and possibilities when charting a course for the future.",
        "Tell me about a time when your strategic vision or big-picture thinking was an asset.",
        "Tell me about a time you were implementing a strategy and had to revise it mid-process due to changes in the environment.",
        "Describe a time you had to develop a strategy that would create value for your organization or customers.",
        "Explain a situation where you had to align your team's goals with the organization's strategic objectives.",
        "Tell me about a time when you identified a long-term opportunity and acted on it.",
        "Describe a time when you had to convince others to buy into your strategic vision."
    ],
}
